# Model arguments
model_name_or_path: princeton-nlp/Llama-3-Base-8B-SFT
torch_dtype: bfloat16
# attn_implementation: flash_attention_2
torch_compile: true

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  argilla/Capybara-Preferences: 1.0
dataset_splits:
- train
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
dpo_lambda: 0.7
do_eval: true
evaluation_strategy: steps
eval_steps: 50
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: zephyr-7b-dpo-full
learning_rate: 5.0e-7
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 1792
max_prompt_length: 1792
num_train_epochs: 1
optim: paged_adamw_32bit
output_dir: data/zephyr-7b-dpo-full
overwrite_output_dir: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: False
save_strategy: "steps"
save_steps: 10
save_total_limit: 1
seed: 42
warmup_ratio: 0.1